# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a016e6a60122dfcdff91bfceb3cfbdc7ce4465722035698c7a79cd5d6a448487fe1f74e6955fd06956bc0f9c583b9ef31b9afab678e2201de19cf4c502bbb1fa

test:
  secret_key_base: 948983f7a0c9d9a092cdd34a92041ebddda8a644fed0e726aaaa4ee2ed50c5c1f9e2a47b83de19f39d4a2290701df9ed774703c2cdabafd034cab75cb5e9c66e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
